# -*- coding: utf-8 -*-
"""Generator of the project figures (schematics, block diagrams, zones) for the
OBD-II simulator, revision v0.7.

The figures are drawn BY HAND here, they are not derived from the board, so they
do not update themselves when the board changes.

    python generate_figures.py

Until 23.08.2026. the drawing calls carried Croatian labels and an English run
translated them through a TRANSLATIONS table at the bottom of this file. The
Croatian pass had not been used since 15.08.2026., so the labels are written in
English directly now and the table is gone. The written documentation uses a
different generator, see PROVENANCE below.
"""
import io, os, sys

W, H = 1600, 1000
INK = "#1c2733"; DIM = "#5c6b7a"; LINE = "#8fa0b0"
ACC = "#b8860b"; RED = "#b03030"; GRN = "#2e7d4f"; BG = "#ffffff"; FILL = "#f3f6f9"

# Stamped into every figure, right inside the root element. These files get
# opened on their own, far from any README, and the two same-named figure sets
# are easy to confuse. No double hyphens anywhere: that is illegal in XML
# comments.
PROVENANCE = ("Generated by hardware/kicad/scripts/generate_figures.py. Repository figure, English. The project's written documentation uses a separate figure set from its own generator, with the same file names but different drawings. Edit this file by editing the generator, never by hand.")

def svg(w, h, body):
    # A double hyphen inside an XML comment makes the file unparseable, and an
    # SVG viewer will simply show nothing. Writing "--lang hr" in the Croatian
    # stamp broke all nine figures on 15.08.2026., so the rule is enforced here
    # rather than trusted.
    if "--" in PROVENANCE:
        raise ValueError("PROVENANCE contains a double hyphen, which is "
                         "illegal inside an XML comment")
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">'
            '<!-- %s -->'
            '<rect width="%d" height="%d" fill="%s"/>'
            '<g font-family="DejaVu Sans, Arial, sans-serif">%s</g></svg>'
            % (w, h, w, h, PROVENANCE, w, h, BG, body))

def box(x, y, w, h, title, sub="", fill=FILL, stroke=INK, tsize=17):
    title = title; sub = sub
    title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    sub = sub.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = '<rect x="%d" y="%d" width="%d" height="%d" rx="6" fill="%s" stroke="%s" stroke-width="2"/>' % (x, y, w, h, fill, stroke)
    s += '<text x="%d" y="%d" text-anchor="middle" font-size="%d" font-weight="600" fill="%s">%s</text>' % (x+w/2, y+(24 if sub else h/2+6), tsize, INK, title)
    if sub:
        for i, ln in enumerate(sub.split("|")):
            s += '<text x="%d" y="%d" text-anchor="middle" font-size="13" fill="%s">%s</text>' % (x+w/2, y+46+i*17, DIM, ln)
    return s

def wire(pts, color=INK, w=2, dash=None):
    d = " ".join(("M %d %d" % p) if i == 0 else ("L %d %d" % p) for i, p in enumerate(pts))
    da = ' stroke-dasharray="6 4"' if dash else ''
    return '<path d="%s" fill="none" stroke="%s" stroke-width="%d"%s/>' % (d, color, w, da)

def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def lbl(x, y, t, size=13, anchor="start", color=DIM, weight="400", mono=True):
    t = esc(t)
    fam = ' font-family="DejaVu Sans Mono, Consolas, monospace"' if mono else ''
    return '<text x="%d" y="%d" text-anchor="%s" font-size="%d" fill="%s" font-weight="%s"%s>%s</text>' % (x, y, anchor, size, color, weight, fam, t)

def title(t, sub=""):
    t = t; sub = sub
    s = '<text x="40" y="46" font-size="26" font-weight="700" fill="%s">%s</text>' % (INK, t)
    if sub: s += '<text x="40" y="72" font-size="15" fill="%s">%s</text>' % (DIM, sub)
    s += '<line x1="40" y1="88" x2="%d" y2="88" stroke="%s" stroke-width="2"/>' % (W-40, LINE)
    return s

def dot(x, y, c=INK):
    return '<circle cx="%d" cy="%d" r="4" fill="%s"/>' % (x, y, c)

def gnd(x, y):
    return (wire([(x, y), (x, y+14)]) +
            '<line x1="%d" y1="%d" x2="%d" y2="%d" stroke="%s" stroke-width="2"/>' % (x-11, y+14, x+11, y+14, INK) +
            '<line x1="%d" y1="%d" x2="%d" y2="%d" stroke="%s" stroke-width="2"/>' % (x-7, y+19, x+7, y+19, INK) +
            '<line x1="%d" y1="%d" x2="%d" y2="%d" stroke="%s" stroke-width="2"/>' % (x-3, y+24, x+3, y+24, INK))

OUT = os.path.dirname(os.path.abspath(__file__))
def write(name, w, h, body):
    p = os.path.join(OUT, "fig", name + ".svg")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", encoding="utf-8").write(svg(w, h, body))
    return p

# ─────────────────────────── Schematic 1: power section ─────────────────────
def schema1():
    b = title("Schematic 1: power section",
              "USB-C PD 12 V -> pin 16 of the J1962 connector (tool power) and -> 3.3 V for the logic. Revision v0.7")
    # VBUS trunk runs above every block, so nothing crosses a box.
    b += box(60, 250, 150, 130, "J1", "USB-C 16 pin|VBUS|CC1 / CC2|DP / DM")
    b += box(300, 250, 230, 190, "CH224K (U1)", "USB-C PD sink|ESSOP-10|requests the 12 V profile|Rd on CC built in")
    b += wire([(210, 300), (300, 300)], INK, 2); b += lbl(215, 290, "CC1, CC2", 12)
    # DP and DM of the controller are NOT connected to the USB-C pair. The CH224
    # datasheet, section 5.5, requires exactly that when the A-port protocols are
    # not used.
    # The note goes BELOW the J1 box, not into the 90 px gap between J1 and the
    # controller. It only just fitted there in Croatian and the English label
    # ("NOT connected") ran straight through the CH224K box.
    b += lbl(60, 405, "DP, DM: NOT connected", 12, color=RED)
    # VBUS: up out of the connector, then straight across the top
    b += wire([(135, 250), (135, 130), (1420, 130)], ACC, 3)
    b += dot(135, 250, ACC)
    b += lbl(560, 118, "VBUS = 12 V after the PD contract (5 V on plug-in)", 14, color=ACC, weight="700", mono=False)
    # CH224K taps VBUS for VDD and for the sense pin
    b += wire([(415, 130), (415, 250)], INK, 2); b += dot(415, 130, ACC)
    b += lbl(425, 200, "R21 = 1 kΩ -> VDD, C22 = 1 µF", 12)
    b += wire([(530, 340), (620, 340)], INK, 2)
    b += lbl(540, 330, "R22 = 10 kΩ (sense)", 12)
    b += wire([(620, 340), (620, 130)], INK, 2); b += dot(620, 130, ACC)
    # CFG1 -> Rset -> GND
    b += wire([(415, 440), (415, 480)], ACC, 2)
    b += box(300, 480, 300, 70, "R23 = 24 kΩ", "CFG1 -> ground = 12 V", fill="#fff6e0", stroke=ACC)
    b += wire([(450, 550), (450, 580)]) + gnd(450, 580)
    b += lbl(620, 545, "6.8 k = 9 V   ·   24 k = 12 V   ·   56 k = 15 V   ·   NC = 20 V", 12, color=DIM, mono=False)
    # up: fuse + TVS -> pin 16
    b += dot(860, 130, ACC)
    b += wire([(860, 130), (860, 200)], ACC, 3)
    b += box(790, 200, 110, 70, "F1", "PTC 500 mA", fill="#fff6e0", stroke=ACC)
    b += wire([(900, 235), (950, 235)], ACC, 3)
    # blocking diode between the fuse and the connector
    b += box(950, 200, 130, 70, "D3", "SMAJ16A blocking|anode on F1", fill="#ffe9d6", stroke=RED)
    b += wire([(1080, 235), (1130, 235)], ACC, 3)
    b += box(1130, 200, 120, 70, "D2", "TVS SMAJ16A|cathode on 12 V", fill="#fff6e0", stroke=ACC)
    b += wire([(1190, 270), (1190, 310)]) + gnd(1190, 310)
    b += wire([(1250, 235), (1300, 235)], ACC, 3)
    b += box(1300, 200, 160, 130, "J1962F (J2)", "pin 16: +12 V|pin 6/14: CAN-H/L|pin 4/5: ground",
             fill="#fff6e0", stroke=ACC)
    b += lbl(790, 300, "powers the diagnostic tool, just like a vehicle", 14, color=ACC, weight="600", mono=False)
    # down: buck -> 3.3 V
    b += dot(760, 130, ACC)
    b += wire([(760, 130), (760, 440), (860, 440)], ACC, 3)
    b += box(860, 400, 220, 130, "TPS562201 (U2)",
             "step-down converter|input 4.5 - 17 V, output 2 A|L2 = 4.7 µH, C3/C4 = 22 µF low ESR|FB 51 k / (15 k + 470 Ω)|C21 bootstrap 5.8 mm from the BST pin")
    b += wire([(1080, 460), (1240, 460)], GRN, 3)
    b += lbl(1100, 450, "+3.3 V", 15, color=GRN, weight="700")
    b += box(1240, 425, 300, 70, "device logic",
             "ESP32-S3, MCP2515, SN65HVD230, ILI9341, S25FL128L", fill="#eef7f1", stroke=GRN)
    b += wire([(970, 530), (970, 565)]) + gnd(970, 565)
    # second buck: 12 V -> 5 V for the USB stick (added 18.07.2026.)
    b += dot(1200, 130, ACC)
    b += wire([(1200, 130), (1200, 555), (1240, 555)], ACC, 3)
    b += box(1240, 520, 300, 100, "TPS562201 (U11)",
             "second step-down converter, 5 V|L3 = 4.7 µH, FB R24/R25 = 51 k / 9.31 k|C37 = 10 µF at the U10 switch input")
    b += lbl(1150, 650, "the 5 V output powers the USB stick through switch U10", 13, color=GRN, weight="600", mono=False)
    b += lbl(60, 650, "The converter input range (4.5 - 17 V) covers both the 5 V before the PD contract and the 12 V after it, so the logic comes up either way.", 14, color=DIM, mono=False)
    b += lbl(60, 676, "The charger has to support the 12 V PD profile (20 W or more). Peak input load is about 12 W, that is 1 A at 12 V.", 14, color=DIM, mono=False)
    b += lbl(60, 712, "D3 (SMAJ16A forward biased) passes the board -> tool direction only. Fuse F1 is a PTC and conducts both ways, so without the diode an external 12 V", 14, color=RED, mono=False)
    b += lbl(60, 736, "from a tool that powers pin 16 itself would flow back into VBUS, into both converter inputs and onto the USB-C connector VBUS.", 14, color=RED, mono=False)
    return write("schema1", W, 770, b)

# ─────────────────────────── Schematic 2: CAN interface ──────────────────────
def schema2():
    b = title("Schematic 2: CAN interface", "MCP2515 -> SN65HVD230 -> ESD protection -> J1962F connector. The 120 Ω termination and the ESD sit just outside the connector body. Revision v0.7")
    b += box(60, 150, 230, 230, "MCP2515 (U4)", "CAN 2.0B controller, SPI|crystal Y1 = 8 MHz|C6, C7 = 22 pF|500 kbit/s")
    for i, (sig, pin, y) in enumerate([("MOSI", "GPIO11", 170), ("MISO", "GPIO13", 200), ("SCK", "GPIO12", 230), ("CS-CAN", "GPIO10", 260), ("INT-CAN", "GPIO9", 290)]):
        b += wire([(60, y), (0, y)], LINE, 0)
        # The label goes ABOVE the wire and is left-aligned. Right-aligned at
        # x = 55 it ran off the canvas (the longest one is 13 characters, so it
        # started at -39).
        b += lbl(2, y - 4, "%s (%s)" % (sig, pin), 12, anchor="start")
    b += lbl(2, 326, "to ESP32-S3 (U6)", 12, anchor="start", color=ACC)
    b += wire([(290, 200), (420, 200)]); b += lbl(310, 190, "TXCAN")
    b += wire([(290, 250), (420, 250)]); b += lbl(310, 240, "RXCAN")
    b += box(420, 150, 200, 180, "SN65HVD230 (U5)", "3.3 V transceiver|RS to ground (high-speed mode)|ISO 11898")
    # ORDER CORRECTED. The figure used to draw U5 -> D1 -> R7 -> J2, i.e. the ESD
    # closer to the transceiver and the termination closer to the connector,
    # which is the reverse of what the checklist requires and of what is on the
    # board. Now the termination comes first, then the ESD, then the connector.
    b += wire([(620, 200), (870, 200)], RED, 3); b += lbl(640, 190, "CAN-H", 13, color=RED)
    b += wire([(620, 250), (870, 250)], "#2a5db0", 3); b += lbl(640, 265, "CAN-L", 13, color="#2a5db0")
    b += dot(700, 200, RED) + dot(700, 250, "#2a5db0")
    b += '<rect x="680" y="205" width="40" height="40" fill="none" stroke="%s" stroke-width="2"/>' % INK
    b += lbl(660, 285, "R7 = 120 Ω", 13)
    b += box(870, 150, 170, 150, "D1", "PESD1CAN|CAN ESD protection|SOT-23")
    b += wire([(1040, 200), (1080, 200)], RED, 3)
    b += wire([(1040, 250), (1080, 250)], "#2a5db0", 3)
    b += box(1080, 120, 200, 260, "J1962F (J2)", "pin 6: CAN-H|pin 14: CAN-L|pin 4, 5: ground|pin 16: +12 V", fill="#fff6e0", stroke=ACC)
    b += wire([(1180, 380), (1180, 420), (1360, 420)], ACC, 3)
    b += box(1360, 385, 180, 70, "12 V from schematic 1", "through F1, D3 and D2", fill="#fff6e0", stroke=ACC)
    # Test points on the CAN pair, in line between the termination and the ESD diode
    b += dot(800, 200, RED) + dot(800, 250, "#2a5db0")
    b += wire([(800, 200), (800, 150)], LINE, 2)
    b += wire([(800, 250), (770, 250), (770, 320)], LINE, 2)
    b += lbl(775, 140, "TP3", 12, color=DIM)
    b += lbl(740, 340, "TP4", 12, color=DIM)
    b += lbl(60, 430, "C12, C5 = decoupling capacitors at the supply pins of both chips (9.0 and 13.5 mm from the pin).", 14, color=DIM, mono=False)
    b += lbl(60, 454, "The pair is routed by a dedicated script BEFORE Freerouting, so the chain is unbroken, with no branches and not a single", 14, color=RED, mono=False)
    b += lbl(60, 478, "via, entirely on the top layer. Machine routed, the pair had the ESD diode on a 13.0 mm stub (CANH) and 4.3 mm (CANL), and CANL", 14, color=RED, mono=False)
    b += lbl(60, 502, "had a via. Test points TP3 and TP4 are in line, between the termination and the ESD diode.", 14, color=RED, mono=False)
    b += lbl(60, 530, "The pair length mismatch is about 20 mm and cannot be smaller: it comes from the R7 leads spaced 10.16 mm apart and the two pin rows", 13, color=DIM, mono=False)
    b += lbl(60, 552, "of the J1962F connector spaced 8.6 mm apart. At 500 kbit/s that is 0.13 ns on a 2000 ns bit.", 13, color=DIM, mono=False)
    return write("schema2", W, 590, b)

# ─────────────────────────── Schematic 3: MCU + memory + USB ─────────────────
def schema3():
    b = title("Schematic 3: ESP32-S3-WROOM-1, external flash and USB subsystem", "ESP32-S3 pin numbering. Revision v0.7, with SPI series termination and test points")
    b += box(560, 130, 300, 480, "ESP32-S3-WROOM-1 (U6)", "dual core 240 MHz|8 MB flash, 512 KB SRAM|the only SPI master")
    left = [("MOSI -> R31 33 Ω", "GPIO11", 220), ("MISO", "GPIO13", 250), ("SCK -> R30 33 Ω", "GPIO12", 280),
            ("CS-CAN", "GPIO10", 320), ("INT-CAN", "GPIO9", 350),
            ("CS-TFT", "GPIO14", 390), ("DC/RS", "GPIO21", 420), ("RST-TFT", "GPIO47", 450),
            ("CS-FLASH", "GPIO15", 490),
            # programming circuit (below the S25FL128L box, which ends at y=550)
            ("RESET (SW5, R13 + C26)", "EN", 570), ("BOOT (SW4, R14)", "GPIO0", 600)]
    for sig, pin, y in left:
        b += wire([(560, y), (400, y)])
        b += lbl(395, y+5, "%s  %s" % (pin, sig), 13, anchor="end")
    right = [("ENC-A", "GPIO1", 220, ""), ("ENC-B", "GPIO38", 250, ""), ("ENC-SW", "GPIO39", 280, ""),
             ("JOY-X", "GPIO2", 310, "ADC1_CH1"), ("JOY-Y", "GPIO4", 340, "ADC1_CH3"),
             ("JOY-SW", "GPIO5", 370, ""), ("SW1 CONFIRM", "GPIO6", 400, ""), ("SW2 CLEAR", "GPIO7", 430, ""),
             ("SW3 RETURN", "GPIO8", 460, ""), ("USB-SEL (pull-down R15)", "GPIO16", 500, ""), ("USB-HOST-EN", "GPIO17", 530, ""),
             ("USB D-", "GPIO19", 500, "fixed OTG"), ("USB D+", "GPIO20", 530, "fixed OTG"),
             ("TX0 / RX0, header J6 (UART)", "GPIO43/44", 560, "")]
    for sig, pin, y, extra in right:
        b += wire([(860, y), (1010, y)])
        b += lbl(1015, y+5, "%s  %s %s" % (pin, sig, ("(" + extra + ")") if extra else ""), 13)
    b += box(120, 430, 230, 120, "S25FL128L (U7)", "16 MB NOR flash, SPI|FAT filesystem with the scenarios|WP and HOLD on +3.3 V")
    b += wire([(350, 490), (400, 490)])
    # The SPI series termination. The box goes into the empty space at the TOP
    # LEFT rather than into the corridor between the pin labels and the module
    # (x 400..560), where it would cut across all eleven wires.
    # The left column x 120..395 is full of pin labels up to y = 600, so the box
    # goes below them, into the band y 650..760, which is free up to the USB-C
    # box at x = 600.
    b += box(120, 650, 250, 110, "R30, R31", "33 Ω in series on SCK and MOSI|right at the module pin|SCK 4.0 mm, MOSI 10.5 mm",
             fill="#ffe9d6", stroke=RED)
    b += box(1180, 600, 250, 100, "TS3USB221 (U9)", "USB mux: USB-C or USB-A")
    b += box(1180, 720, 250, 90, "SY6280 (U10)", "stick power switch|5 V from converter U11")
    b += wire([(1120, 500), (1160, 500), (1160, 650), (1180, 650)], LINE, 2)
    b += wire([(1120, 470), (1140, 470), (1140, 765), (1180, 765)], LINE, 2)
    b += box(600, 660, 200, 90, "USB-C (J1)", "MSC link to a computer|D4 USBLC6-2SC6")
    b += box(870, 660, 200, 90, "USB-A (J4)", "USB stick|D5 USBLC6-2SC6")
    b += wire([(800, 705), (1180, 660)], LINE, 2, True)
    b += wire([(1070, 705), (1180, 690)], LINE, 2, True)
    b += lbl(600, 790, "One USB OTG controller, so mux U9 switches it between USB-C and USB-A, with the stick taking precedence.", 14, color=DIM, mono=False)
    b += lbl(600, 828, "Programming: USB-Serial-JTAG over USB-C (R15 holds the mux on the USB-C side during reset), the BOOT and RESET buttons, monitor on J6.", 14, color=DIM, mono=False)
    b += lbl(120, 630, "The hatched area along the right edge of the module is the copper keep-out under the antenna (3 - 5 mm).", 14, color=DIM, mono=False)
    b += lbl(120, 130, "The strapping pins (3, 45, 46) and the flash/PSRAM range (26 - 37) are avoided, and GPIO0 carries only the BOOT button (SW4).", 14, color=DIM, mono=False)
    b += lbl(120, 866, "SPI: the bus is 88 to 126 mm long and carries three loads (U4, U7, J5), so series termination at the source damps the reflection.", 14, color=RED, mono=False)
    b += lbl(120, 890, "R30 and R31 of 33 Ω right at the output pin damp the reflection from the far end. Past the resistor lies net SCK / MOSI, while the module pin", 14, color=RED, mono=False)
    b += lbl(120, 914, "drives net SCK_MCU and MOSI_MCU. Both CS lines (CS_CAN, CS_FLASH) have a 10 kΩ pull-up (R35, R36).", 14, color=RED, mono=False)
    b += lbl(600, 866, "Both USB ports have ESD protection (D4, D5, USBLC6-2SC6). Pin 5 of those diodes goes to +3.3 V, not to VBUS,", 14, color=RED, mono=False)
    b += lbl(600, 890, "because VBUS carries 12 V after the PD contract, while that pin stands off 5.25 V. USB_HOST_EN got the pull-down R37.", 14, color=RED, mono=False)
    b += lbl(120, 948, "Test points TP5 (MOSI), TP6 (MISO) and TP7 (SCK) tap at flash U7, that is at the middle of the bus, 4 to 5 mm from", 14, color=DIM, mono=False)
    b += lbl(120, 972, "its leads, so they add no long stub. TP1 (3.3 V) and TP2 (ground) are on the display header, TP8 (VBUS) next to fuse F1.", 14, color=DIM, mono=False)
    return write("schema3", W, 1000, b)

# ─────────────────────────── Schematic 4: user interface ─────────────────────
def schema4():
    b = title("Schematic 4: user interface section", "ILI9341, encoder ENC1, the 5-way switch SW6 and the CONFIRM / CLEAR / RETURN buttons. Revision v0.7, with the encoder filter at both ends")
    b += box(80, 140, 260, 200, "Waveshare 18366 (on J5)", "ILI9341, 2.4 inch TFT, 320 × 240|SPI (no MISO), no touch|BL input through R8 = 33 Ω|external module, on header J5")
    for sig, pin, y in [("CS-TFT", "GPIO14", 170), ("DC/RS", "GPIO21", 200), ("RST-TFT", "GPIO47", 230), ("SPI", "MOSI/SCK (no MISO)", 270)]:
        b += wire([(340, y), (470, y)])
        b += lbl(475, y+5, "%s  %s" % (pin, sig), 13)
    b += box(80, 400, 260, 110, "ENC1", "encoder EN11-HSB1AQ20|20 pulses per revolution, with a push button|A -> GPIO1, B -> GPIO38, button -> GPIO39")
    b += wire([(340, 455), (378, 455)])
    # 10 k pull-up to 3.3 V and a capacitor to ground on all three contacts
    b += box(378, 400, 190, 110, "R38-R40, R32-R34, C31-C33", "100 Ω in series at the contact|pull-up 10 kΩ to +3.3 V|47 nF to ground",
             fill="#ffe9d6", stroke=RED)
    b += wire([(568, 455), (600, 455)])
    b += box(600, 415, 150, 80, "C34-C36", "1 nF to ground|at the module pin",
             fill="#ffe9d6", stroke=RED)
    b += wire([(750, 455), (760, 455)])
    b += lbl(600, 405, "GPIO1 / 38 / 39", 12)
    b += box(80, 550, 260, 130, "SW6", "Alps SKRHABE010, 5 directions|X axis -> GPIO2 (ADC1_CH1)|Y axis -> GPIO4 (ADC1_CH3)|click -> GPIO5; R26-R29 ladder")
    b += wire([(340, 615), (470, 615)]); b += lbl(475, 620, "GPIO2 / GPIO4 / GPIO5", 13)
    for i, (name, pin) in enumerate([("SW1 CONFIRM", "GPIO6"), ("SW2 CLEAR", "GPIO7"), ("SW3 RETURN", "GPIO8")]):
        y = 720 + i*70
        b += box(80, y, 260, 55, name, "")
        b += wire([(340, y+27), (470, y+27)])
        b += lbl(475, y+32, "%s  %s" % (pin, "(pull-up 10 kΩ, active low)"), 13)
    b += box(760, 300, 300, 320, "ESP32-S3-WROOM-1 (U6)", "GPIO1, GPIO2, GPIO4: ADC1|GPIO5 - GPIO8: digital inputs|GPIO14, GPIO21, GPIO47: display")
    b += wire([(700, 455), (760, 455)], LINE, 2)
    b += lbl(760, 660, "The external pull-up resistors R9 - R12 (10 kΩ) are kept for noise immunity,", 14, color=DIM, mono=False)
    b += lbl(760, 684, "even though the ESP32-S3 has internal pull-ups too. The same goes for the encoder (R32 - R34).", 14, color=DIM, mono=False)
    b += box(760, 140, 300, 110, "J1962F", "OBD-II connector along the top edge,|above the display|pin 16 carries 12 V for the tool", fill="#fff6e0", stroke=ACC)
    b += lbl(80, 955, "Encoder: A and B are decoded in an interrupt, where mechanical contact bounce produces false steps. That is why each of the three", 14, color=RED, mono=False)
    b += lbl(80, 979, "contacts has 100 Ω in series, a 10 kΩ pull-up to 3.3 V and 47 nF to ground. The series resistor protects the contact from the discharge current,", 14, color=RED, mono=False)
    b += lbl(80, 1003, "and the firmware still debounces. Without that filter, A, B and the button would hang on the internal pull-ups alone.", 14, color=RED, mono=False)
    b += lbl(80, 1037, "The second capacitor (C34 - C36, 1 nF each) sits right at the module input pin, 4.3 to 11.0 mm from it. Past the filter at the encoder", 14, color=RED, mono=False)
    b += lbl(80, 1061, "the signal travels another 125 to 154 mm across the board, alongside the SPI bus, and the node is high impedance (10 kΩ). That capacitor does not", 14, color=RED, mono=False)
    b += lbl(80, 1085, "serve debouncing but shunts picked-up noise right at the input, which is why it is 1 nF and not 47 nF.", 14, color=RED, mono=False)
    return write("schema4", W, 1110, b)

# ─────────────────────────── Figure 1: block diagram ─────────────────────────
def blok():
    b = title("Block diagram of the OBD-II simulator", "Five functional blocks, revision v0.7")
    b += box(640, 300, 300, 160, "Microcontroller", "ESP32-S3-WROOM-1|the only SPI master", fill="#eef2f7")
    b += box(120, 300, 260, 160, "CAN and OBD interface", "MCP2515 + SN65HVD230|ESD protection, J1962F|120 Ω termination")
    b += box(120, 60, 260, 170, "Power", "USB-C + CH224K (PD 12 V)|TPS562201 -> 3.3 V|12 V -> pin 16 (F1, D3, D2)", fill="#fff6e0", stroke=ACC)
    b += box(1200, 300, 280, 160, "User interface", "ILI9341, EN11 encoder|5-way switch, three buttons")
    b += box(640, 600, 300, 160, "Memory and USB", "S25FL128L (FAT)|TS3USB221, SY6280|USB-C and USB-A")
    b += wire([(380, 380), (640, 380)], INK, 3); b += lbl(430, 370, "SPI + INT")
    b += wire([(940, 380), (1200, 380)], INK, 3); b += lbl(1000, 370, "SPI + ADC + GPIO")
    b += wire([(790, 460), (790, 600)], INK, 3); b += lbl(800, 540, "SPI + USB OTG")
    b += wire([(250, 230), (250, 300)], ACC, 3); b += lbl(260, 270, "3.3 V", 13, color=ACC)
    b += wire([(380, 145), (560, 145), (560, 300), (640, 300)], ACC, 3); b += lbl(400, 135, "3.3 V to every block", 13, color=ACC)
    b += wire([(250, 460), (250, 520), (60, 520)], ACC, 3)
    b += lbl(70, 545, "12 V on connector pin 16: the simulator powers the diagnostic tool like a real vehicle", 14, color=ACC, weight="600", mono=False)
    b += box(1200, 60, 280, 130, "Diagnostic tool", "ELM327, handheld scanner|powered from the simulator", fill="#f7f0e6", stroke=ACC)
    b += wire([(380, 380), (380, 125), (1200, 125)], ACC, 2, True)
    return write("blok", W, 820, b)

# ─────────────────────────── Figure 2: CAN chain ─────────────────────────────
def canchain():
    b = title("CAN chain", "MCP2515 -> SN65HVD230 -> 120 Ω termination -> ESD protection -> J1962F connector")
    xs = [("MCP2515", "controller, SPI"), ("SN65HVD230", "transceiver"), ("R7 120 Ω", "termination"), ("PESD1CAN", "ESD protection"), ("J1962F", "OBD-II connector")]
    for i, (n, s) in enumerate(xs):
        x = 40 + i*300
        last = (i == len(xs) - 1)
        b += box(x, 160, 230, 120, n, s, fill="#fff6e0" if last else FILL, stroke=ACC if last else INK)
        if not last:
            b += wire([(x+230, 220), (x+300, 220)], INK, 3)
    b += lbl(285, 205, "TXCAN / RXCAN", 12)
    b += lbl(585, 205, "CAN-H / CAN-L", 12)
    b += lbl(885, 205, "same pair", 12)
    b += lbl(1185, 205, "same pair", 12)
    b += lbl(40, 330, "The order is prescribed and that is how it is actually routed: termination before the ESD diode, the ESD diode right at the connector.", 13, color=DIM, mono=False)
    b += lbl(40, 356, "D1 is 9.0 mm from pin 14, R7 is 4.0 mm from D1. Closer is impossible: the J1962F contacts sit inside a 43.3 x 20.7 mm body.", 13, color=DIM, mono=False)
    b += lbl(40, 384, "Connector pin 16 carries 12 V from the power section, through F1 and the blocking diode D3 (SMAJ16A).", 13, color=ACC, mono=False)
    return write("canchain", W, 420, b)

# ─────────────────────────── Figure 3: CH224K detail ─────────────────────────
def ip2368():
    b = title("External circuit of the CH224K USB-C PD sink controller",
              "One resistor selects the voltage, the charger puts it on VBUS")
    b += box(600, 150, 340, 280, "CH224K (U1)",
             "ESSOP-10|USB-C PD sink|PD3.0/2.0, 4 - 22 V|Rd on the CC lines built in")
    b += box(140, 190, 200, 130, "USB-C (J1)", "VBUS|CC1, CC2|DP, DM")
    b += wire([(340, 230), (600, 230)], INK, 2); b += lbl(400, 220, "CC1, CC2")
    b += wire([(340, 285), (600, 285)], INK, 2); b += lbl(400, 275, "DP, DM")
    # VBUS rail across the top
    b += wire([(240, 190), (240, 90), (1420, 90)], ACC, 3)
    b += dot(240, 190, ACC)
    b += lbl(900, 78, "VBUS: 5 V on plug-in, 12 V after the PD contract", 15, color=ACC, weight="700", mono=False)
    # VDD: series resistor + cap
    b += wire([(700, 90), (700, 150)], INK, 2); b += dot(700, 90, ACC)
    b += box(640, 100, 120, 0, "", "")
    b += lbl(715, 130, "R21 = 1 kΩ", 13)
    b += wire([(700, 430), (700, 470)]); b += lbl(600, 490, "C22 = 1 µF on VDD (pin 1)", 13)
    # VBUS sense
    b += wire([(940, 200), (1120, 200)], INK, 2)
    b += box(1120, 165, 150, 70, "R22", "10 kΩ", fill="#fff6e0", stroke=ACC)
    b += wire([(1270, 200), (1420, 200), (1420, 90)], INK, 2)
    b += lbl(950, 190, "VBUS sense (pin 8)", 13)
    # CFG1 -> Rset
    b += wire([(940, 330), (1120, 330)], ACC, 3)
    b += box(1120, 295, 300, 80, "R23 = 24 kΩ", "CFG1 (pin 9) -> ground = 12 V", fill="#fff6e0", stroke=ACC)
    b += wire([(1270, 375), (1270, 415)]) + gnd(1270, 415)
    b += lbl(950, 320, "CFG1", 13, color=ACC)
    b += lbl(1120, 450, "6.8 kΩ = 9 V   ·   24 kΩ = 12 V   ·   56 kΩ = 15 V   ·   NC = 20 V", 13, color=DIM, mono=False)
    b += lbl(140, 560, "CFG2 and CFG3 stay unconnected (single resistor selection). The chip ground is the exposed pad only (pin 0).", 14, color=DIM, mono=False)
    b += lbl(140, 586, "The pinout was checked against the reference schematic in the WCH CH224DS1 datasheet, not against the pin table, which lists a different CFG pin order.", 14, color=DIM, mono=False)
    return write("ip2368", W, 630, b)

# ─────────────────────────── PCB: zones and layout ───────────────────────────
import json
# The rectangles are kept in step with ZONES in build_board.py and with the
# 130 x 115 mm outline. They used to be a leftover from the 100 x 80 revision and
# described neither the current board nor its immediate predecessor.
ZONES = {
    "Power": (56, 46, 106, 93, "#fff2d6"),
    "CAN": (2, 50, 44, 93, "#ffe4e1"),
    "OBD connector": (10, 92, 54, 114, "#fff2d6"),
    "MCU, memorija i USB": (34, 2, 106, 45, "#e6f0fb"),
    "User interface": (94, 8, 127, 92, "#e9f6ee"),
}
# The board size is read from the actual .kicad_pcb when pcbnew is available,
# so the figure cannot fall behind the placement. Without pcbnew the last
# known values are used.
BW_MM, BH_MM = 130.0, 115.0
FP_POS = {}
try:
    import pcbnew as _pcb
    _bp = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                       "obd2-simulator.kicad_pcb")
    _b = _pcb.LoadBoard(_bp)
    _bb = _b.GetBoardEdgesBoundingBox()
    _x0 = _pcb.ToMM(_bb.GetX()); _y1 = _pcb.ToMM(_bb.GetY() + _bb.GetHeight())
    BW_MM = round(_pcb.ToMM(_bb.GetWidth()))
    BH_MM = round(_pcb.ToMM(_bb.GetHeight()))
    for _fp in _b.GetFootprints():
        _p = _fp.GetPosition()
        FP_POS[_fp.GetReference()] = (_pcb.ToMM(_p.x) - _x0, _y1 - _pcb.ToMM(_p.y))
except Exception as _e:                       # pokrenuto obicnim pythonom
    print("note: pcbnew unavailable (%s), falling back to the stored size" % _e)

SC = 13  # mm -> px
MX, MY = 90, 120
def bx(x): return MX + x*SC
def by(y): return MY + (BH_MM-y)*SC   # y measured from the bottom

def zone_box(refs, pad=4.0):
    """Bounding box of a component group, from the actual board positions."""
    pts = [FP_POS[r] for r in refs if r in FP_POS]
    if not pts:
        return None
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    return (max(0.5, min(xs) - pad), max(0.5, min(ys) - pad),
            min(BW_MM - 0.5, max(xs) + pad), min(BH_MM - 0.5, max(ys) + pad))

def board_fig(name="zones", ttl="Functional zone layout on the printed circuit board",
              sub="Two-layer FR4 130 × 115 mm, revision v0.7"):
    ZKOMP = {
        "OBD connector": ["J2 SEP-A-OBD-D2", "R7 120 Ω", "D1 PESD1CAN",
                         "F1 PTC 500 mA", "D2 TVS SMAJ16A", "D3 SMAJ16A"],
        "Power": ["J1 USB-C", "U1 CH224K", "R23 24 kΩ (12 V)", "C1 100 µF",
                      "U2 TPS562201 (3.3 V)", "U11 TPS562201 (5 V)", "L2/L3 4.7 µH"],
        "CAN": ["U4 MCP2515", "Y1 8 MHz", "U5 SN65HVD230", "C6/C7 22 pF"],
        "Microcontroller": ["U6 ESP32-S3-WROOM-1", "J5 LCD (Waveshare)",
                           "U7 S25FL128L", "R8 33 Ω"],
        "Memory and USB": ["J4 USB-A", "U9 TS3USB221", "U10 SY6280"],
        "User interface": ["ENC1 EN11 encoder", "SW6 SKRHABE010", "SW1 CONFIRM",
                               "SW2 CLEAR", "SW3 RETURN", "R9 - R12 pull-up"],
    }
    # The extent of every zone is computed from the actual positions on the board.
    ZREFS = {
        "OBD connector": ["J2", "R7", "D1", "F1", "D2"],
        "Power": ["J1", "U1", "U2", "U11", "C1", "L2", "L3", "C3", "C4",
                      "C27", "C28", "R16", "R17A", "R17B", "R24", "R25",
                      "SW4", "SW5", "J6"],
        "CAN": ["U4", "U5", "Y1", "C6", "C7", "C10", "C11", "C12", "C5"],
        "Microcontroller": ["U6", "J5", "U7", "R8", "R13", "C15", "C16", "C19",
                           "C24", "C25", "C26"],
        "Memory and USB": ["J4", "U9", "U10", "C14", "C18", "C23", "R19", "R15"],
        "User interface": ["ENC1", "SW6", "SW1", "SW2", "SW3",
                               "R9", "R10", "R11", "R12", "R26", "R27", "R28", "R29"],
    }
    ZCOL = {
        "OBD connector": "#fff2d6", "Power": "#fdf0e0", "CAN": "#ffe4e1",
        "Microcontroller": "#eef2f7", "Memory and USB": "#e6f0fb",
        "User interface": "#e9f6ee",
    }
    ZBOX = {}
    for _nm, _refs in ZREFS.items():
        _bx = zone_box(_refs)
        if _bx:
            ZBOX[_nm] = (_bx[0], _bx[1], _bx[2], _bx[3], ZCOL[_nm])
    b = title(ttl, sub)
    b += '<rect x="%d" y="%d" width="%d" height="%d" rx="8" fill="#fbfcfd" stroke="%s" stroke-width="3"/>' % (
        bx(0), by(BH_MM), BW_MM*SC, BH_MM*SC, INK)
    for nm, (x1, y1, x2, y2, col) in ZBOX.items():
        b += '<rect x="%d" y="%d" width="%d" height="%d" rx="4" fill="%s" stroke="%s" stroke-width="1.5" stroke-dasharray="6 4"/>' % (
            bx(x1), by(y2), (x2-x1)*SC, (y2-y1)*SC, col, DIM)
        b += lbl(bx(x1)+10, by(y2)+22, nm, 15, color=INK, weight="700", mono=False)
        for i, c in enumerate(ZKOMP[nm]):
            hot = c.startswith(("J2 SEP", "ENC1", "SW6", "J4", "D2"))
            b += lbl(bx(x1)+14, by(y2)+48+i*22, "• " + c, 13,
                     color=ACC if hot else DIM, weight="600" if hot else "400", mono=False)
    for _hr in ("H1", "H2", "H3", "H4"):
        if _hr in FP_POS:
            _hx, _hy = FP_POS[_hr]
            b += '<circle cx="%d" cy="%d" r="8" fill="none" stroke="%s" stroke-width="2"/>' % (
                bx(_hx), by(_hy), DIM)
    b += lbl(bx(BW_MM/2), by(BH_MM)-16, "%d mm" % BW_MM, 14, anchor="middle", color=DIM)
    b += lbl(bx(0)-78, by(BH_MM/2), "%d mm" % BH_MM, 14, color=DIM)
    y0 = by(0) + 46
    b += lbl(MX, y0, "The OBD connector J2 and USB-C J1 share the top edge, USB-A J4 is on the bottom one. The interface sits on a single vertical axis along the right edge.", 14, color=ACC, mono=False)
    b += lbl(MX, y0+24, "Every passive is THT and the resistors lie flat, which is why the board grew to %d × %d mm. Components are on the top side only." % (BW_MM, BH_MM), 14, color=DIM, mono=False)
    return write(name, int(BW_MM*SC) + 2*MX, int(BH_MM*SC) + MY + 110, b)

# ─────────────────────────── Net overview ────────────────────────────────────
def nets():
    rows = [("SPI", "MOSI GPIO11, MISO GPIO13, SCK GPIO12", "33 Ω in series (R30, R31) at the source, bus 88 to 126 mm, width 0.20 mm"),
            ("Chip select", "CS-CAN GPIO10, CS-TFT GPIO14, CS-FLASH GPIO15", "every peripheral has its own line"),
            ("Interrupt", "INT-CAN GPIO9", "dedicated pin, pull-up 10 kΩ"),
            ("Display", "DC/RS GPIO21, RST-TFT GPIO47", "alongside the SPI bus"),
            ("Analogue inputs", "JOY-X GPIO2, JOY-Y GPIO4", "ADC1 channels, the SW6 axes through the R26-R29 ladder"),
            ("Encoder", "ENC-A GPIO1, ENC-B GPIO38, ENC-SW GPIO39", "100 R in series, pull-up 10 kΩ and 47 nF at the encoder, another 1 nF at the module pin"),
            ("Buttons", "JOY-SW GPIO5, SW1 GPIO6, SW2 GPIO7, SW3 GPIO8", "active low, pull-up 10 kΩ"),
            ("USB", "USB-SEL GPIO16, USB-HOST-EN GPIO17, D-/D+ GPIO19/20", "D-/D+ routed together, two vias each, mostly on the bottom layer"),
            ("CAN pair", "CAN-H, CAN-L", "0.20 mm, chain with no stubs and no vias, entirely on the top layer"),
            ("Test points", "TP1 3V3, TP2 GND, TP3/TP4 CAN, TP5-TP7 SPI, TP8 VBUS", "each at the pad of its own net, stub 4 to 5 mm (TP1/TP2 up to 15 mm)"),
            ("Programming", "BOOT GPIO0, EN, TX0/RX0 GPIO43/44", "buttons SW4/SW5, header J6, pull-up 10 kΩ, pull-down R15"),
            ("Power", "VBUS 12 V, FUSED_12V, OBD_12V, +3.3 V, GND", "0.20 mm, with the Power class at 0.40 mm on the SW and stick branches, ground is a polygon")]
    h = 200 + len(rows)*54
    b = title("Summary of every net on the device", "ESP32-S3 pin assignment and routing rules, revision v0.7")
    b += '<rect x="60" y="120" width="%d" height="44" fill="%s" stroke="%s"/>' % (W-120, "#eef2f7", INK)
    for i, t in enumerate(["Group", "Signals", "Routing rule"]):
        b += lbl([80, 380, 1050][i], 148, t, 15, color=INK, weight="700", mono=False)
    for i, (a, c, d) in enumerate(rows):
        y = 164 + i*54
        b += '<rect x="60" y="%d" width="%d" height="54" fill="%s" stroke="%s" stroke-width="1"/>' % (y, W-120, "#ffffff" if i % 2 else "#fafbfc", LINE)
        b += lbl(80, y+33, a, 14, color=INK, weight="600", mono=False)
        b += lbl(380, y+33, c, 13)
        b += lbl(1050, y+33, d, 13, color=DIM)
    return write("nets", W, h, b)

# ─────────────────────────── Labels: Croatian -> English ─────────────────────
# Only strings that actually differ are listed. Signal names, designators and
# part numbers are the same in both languages and are left alone. Decimal commas
# become decimal points, because that is the English convention.

if __name__ == "__main__":
    out = [schema1(), schema2(), schema3(), schema4(), blok(), canchain(), ip2368(),
           board_fig(),
           nets()]
    for p in out: print(p)
